#!/usr/bin/env bash
################################################        HEADER CODE        ################################################
#
#						Colors
#
# bold
bred="printf \033[1;31m"
bgreen="printf \033[1;32m"
bblue="printf \033[1;34m"
bwhite="printf \033[1;37m"
# high intensity
ired="printf \033[0;91m"
igreen="printf \033[0;92m"
iblue="printf \033[0;94m"
iwhite="printf \033[0;97m"
# no color
off="printf \033[0m"

#
#						Variables
#
distroName="$(cat /etc/*-release | grep -w "NAME")"
distroPrettyName="$(cat /etc/*-release | grep -w "PRETTY_NAME" | sed "s/PRETTY_NAME=//")"
installDirectory="$(pwd)/xmrig"
AutoBuild="$installDirectory/AutoBuild"
deps="$AutoBuild/deps"
libBuild="$AutoBuild/libBuild"
stableColor="\033[0;90m[Stable]"
latestColor="\033[0;90m[Latest]"
configColor="\033[0;90m[Config]"
pathColor="\033[0;90m[Path]"
devColor="\033[0;90m[Dev]"
cleanColor="\033[0;90m[Clean]"
depsColor="\033[0;90m[Dependencies]"
quietColor="\033[0;90m[Quiet]"
libreColor="\033[0;90m[Libre]"
forceColor="\033[0;90m[Force]"
build0="[0/6] Removing old /xmrig/ folder"
build1="[1/6] Pulling XMRig"
build2="[2/6] Creating Build Folders"
build3="[3/6] Building Libuv"
build4="[4/6] Building Hwloc"
build5="[5/6] Building OpenSSL"
build6="[6/6] Building XMRig"

#
#						Build Dependency Install Functions
#
Apt_Build_Dependencies(){ sudo apt install git wget build-essential cmake automake libtool autoconf ;}
Pacman_Build_Dependencies(){ sudo pacman -S git wget base-devel cmake ;}
DNF_Build_Dependencies(){ sudo dnf install -y git wget make cmake gcc gcc-c++ libstdc++-static automake libtool autoconf ;}
Pkg_Build_Dependencies(){ pkg install git wget cmake automake libtool autoconf ;}
Brew_Build_Dependencies(){ brew install cmake wget automake libtool autoconf ;}
Apk_Build_Dependencies(){ apk add git wget make cmake libstdc++ gcc g++ automake libtool autoconf linux-headers ;}

#
#						Prompt/Message Functions
#
YES_no()
{
	$off
	read yn
	if [[ $yn = "" || $yn = "y" || $yn = "Y" ||$yn = "yes" || $yn = "Yes" ]]; then
		Yes
	else
		No
	fi
}
yes_NO()
{
	$off
	read yn
    if [[ $yn = "y" || $yn = "Y" ||$yn = "yes" || $yn = "Yes" ]]; then
		Yes
	elif [[ $yn = "" ]]; then
		No
	else
		No
	fi
}
Build_Message()
{
	if [[ $optionQuiet = "yes" ]]; then
		$bgreen; echo "$1" ;$off
	else
		$bgreen; echo "############      $1      ############" ;$off
	fi
}
End_Message()
{
	echo
	$bgreen; echo "##################################"
	$bgreen; echo "#   XMRig-Auto-Build complete!   #"
	$bgreen; echo "##################################"
	# shows different locations dependent on if source files are deleted or not
	if [[ $optionClean = "yes" ]]; then
	    $bblue; echo -n "XMRig folder Location: "
	    $iwhite; echo $installDirectory
	else
	    $bblue; echo "Location: "
	    $bwhite; echo -n "xmrig: " ;$iwhite; echo "$AutoBuild/xmrig"
	    $bwhite; echo -n "config.json: " ;$iwhite; echo "$AutoBuild/config.json"
	fi
	$off
}
Print_Help()
{
	$igreen; echo "XMRig-Auto-Build Usage:"
	$bwhite; echo -n "Interactive: "
	$off; echo "./XMRig-Auto-Build"
	$bwhite; echo -n "Options: "
	$off; echo "./XMRig-Auto-Build <option> <more options>"
	$off; echo
cat <<EOM
-S    --stable                Use stable libraries
-L    --latest                Use latest development libraries
-C    --config                Allow configuration of the config.json (GNU/Linux only)
-P    --path                  Set install path:  --path=YOUR_PATH_HERE  or  -P=YOUR_PATH_HERE
-D    --dev                   Use the active development branch of XMRig

-c    --clean                 Delete all files except xmrig and config.json at end of build
-d    --deps                  Install build dependencies
-q    --quiet                 Turn off verbose build messages (progress and errors are still shown)
-l    --libre                 Use LibreSSL instead of OpenSSL
-f    --force                 Force overwrite if /xmrig/ folder already exists

-h    --help                  Print this help message

XMRig-Auto-Build, made by: hinto.janaiyo
EOM
}

#
#						Build Functions
#
Build_Dependencies()
{
	case $foundPackageManager in
		apt)
			Apt_Build_Dependencies
			;;
		pacman)
			Pacman_Build_Dependencies
			;;
		dnf)
			DNF_Build_Dependencies
			;;
		pkg)
			Pkg_Build_Dependencies
			;;
		brew)
			Brew_Build_Dependencies
			;;
		apk)
			Apk_Build_Dependencies
			;;
	esac
	if [[ $? != 0 ]]; then
	$bred; echo "Installing build dependencies failed, exiting..."
	exit
	fi
}
Overwrite_XMRig()
{
	if [[ $optionForce = "yes" ]]; then
	    Build_Message "$build0"
	    rm -rf "$installDirectory" > /dev/null
	fi
}
Pull_XMRig()
{
	Build_Message "$build1"
	if [[ $optionPath = "yes" ]]; then
		cd $inputPath
	fi
	if [[ $optionDev = "yes" ]]; then
		git clone -b dev https://github.com/xmrig/xmrig
	else
		git clone https://github.com/xmrig/xmrig
	fi
}
Build_Folders()
{
	Build_Message "$build2"
	mkdir -p $AutoBuild
	mkdir -p $deps
	mkdir -p $deps/include
	mkdir -p $deps/lib
	mkdir -p $libBuild
}
Build_Libuv()
{
	Build_Message "$build3"
	local UV_VERSION="1.44.1"
	cd $libBuild
	if [[ $libVersion = "stable" ]]; then
		wget https://github.com/libuv/libuv/archive/v${UV_VERSION}.tar.gz -O v${UV_VERSION}.tar.gz
		tar -xzf v${UV_VERSION}.tar.gz
		cd libuv-${UV_VERSION}
	else
		git clone -b master https://github.com/libuv/libuv/
		cd libuv
	fi
	./autogen.sh
	./configure --disable-shared
	make -j$(nproc || sysctl -n hw.ncpu || sysctl -n hw.logicalcpu)
	mv -f include/* $deps
	mv -f .libs/libuv.a $deps/lib
}
Build_Hwloc()
{
	Build_Message "$build4"
	local HWLOC_VERSION="2.7.0"
	local HWLOC_V="v2.7"
	cd $libBuild
	if [[ $libVersion = "stable" ]]; then
		wget https://download.open-mpi.org/release/hwloc/$HWLOC_V/hwloc-${HWLOC_VERSION}.tar.gz -O hwloc-${HWLOC_VERSION}.tar.gz
		tar -xzf hwloc-${HWLOC_VERSION}.tar.gz
		cd hwloc-${HWLOC_VERSION}
	else
		git clone -b master https://github.com/open-mpi/hwloc
		cd hwloc
		./autogen.sh
	fi
	./configure --disable-shared --enable-static --disable-io --disable-libudev --disable-libxml2
	make -j$(nproc || sysctl -n hw.ncpu || sysctl -n hw.logicalcpu)
	mv -f include/* $deps
	mv -f hwloc/.libs/libhwloc.a $deps/lib
}
Build_OpenSSL()
{
	Build_Message "$build5"
	local OPENSSL_VERSION="1.1.1n"
	cd $libBuild
	if [[ $libVersion = "stable" ]]; then
		wget https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz -O openssl-${OPENSSL_VERSION}.tar.gz
		tar -xzf openssl-${OPENSSL_VERSION}.tar.gz
		cd openssl-${OPENSSL_VERSION}
	else
		git clone -b "OpenSSL_1_1_1-stable" https://github.com/openssl/openssl
		cd openssl
	fi
	./config -no-shared -no-asm -no-zlib -no-comp -no-dgram -no-filenames -no-cms
	make -j$(nproc || sysctl -n hw.ncpu || sysctl -n hw.logicalcpu)
	mv -f include/* $deps
	mv -f libcrypto.a $deps/lib
	mv -f libssl.a $deps/lib
}
Build_LibreSSL()
{
	Build_Message "[5/6] Building LibreSSL"
	local LIBRESSL_VERSION="3.4.2"
	cd $libBuild
	if [[ $libVersion = "stable" ]]; then
		wget https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-${LIBRESSL_VERSION}.tar.gz -O libressl-${LIBRESSL_VERSION}.tar.gz
		tar -xzf libressl-${LIBRESSL_VERSION}.tar.gz
		cd libressl-${LIBRESSL_VERSION}
	else
		git clone -b master https://github.com/libressl-portable/portable
		cd portable
		./autogen.sh
	fi
	./configure --disable-shared
	make -j$(nproc || sysctl -n hw.ncpu || sysctl -n hw.logicalcpu)
	mv -f include/* $deps
	mv -f crypto/.libs/libcrypto.a $deps/lib
	mv -f ssl/.libs/libssl.a $deps/lib
}
Build_XMRig()
{
	Build_Message "$build6"
	cd "$AutoBuild"
	if [[ $foundPackageManager = "pkg" || $foundPackageManager = "apk" ]]; then
		cmake .. -DXMRIG_DEPS=$deps -DBUILD_STATIC=ON
	elif [[ $foundPackageManager = "brew" ]]; then
		cmake .. -DOPENSSL_ROOT_DIR="$deps/openssl" -DHWLOC_INCLUDE_DIR="$deps/include" -DHWLOC_LIBRARY="$deps/lib/libhwloc.a"
	else
		cmake .. -DXMRIG_DEPS=$deps
	fi
	if [[ $foundPackageManager = "brew" ]]; then
		make -j$(sysctl -n hw.logicalcpu)
	elif [[ $foundPackageManager = "pkg" ]]; then
		make -j$(sysctl -n hw.ncpu)
	else
		make -j$(nproc)
	fi
	cp "$installDirectory/src/config.json" $AutoBuild
}
Build_Fail()
{
	if [[ $? != 0 ]]; then
		$bred; echo "XMRig-Auto-Build failed building $1..."
		$bred; echo -n "Remove all XMRig-Auto-Build files? (Y/n) " ;$off
		Yes()
		{
			$iwhite; echo "Removing..."
			rm -rf "$AutoBuild" &&$green&& echo "Removed!"
		}
		No(){ $iwhite; echo "Skipping..." ;}
		YES_no
		$bred; echo -n "Remove /xmrig/ folder? (Y/n) " ;$off
		Yes()
		{
			$iwhite; echo "Removing..."
			rm -rf "$installDirectory" &&$green&& echo "Removed!"
		}
		No(){ $iwhite; echo "Skipping..." ;}
		YES_no
		$ired; echo "Exiting XMRig-Auto-Build: $1 failed to build..."
		exit
	fi
}
Build_All()
{
	Overwrite_XMRig;Pull_XMRig;Build_Fail "XMRig"
	Build_Folders;Build_Fail "Folders"
	Build_Libuv;Build_Fail "Libuv"
	Build_Hwloc;Build_Fail "Hwloc"
	if [[ $optionLibre = "yes" ]]; then
		Build_LibreSSL;Build_Fail "LibreSSL"
	else
		Build_OpenSSL;Build_Fail "OpenSSL"
	fi
	Build_XMRig;Build_Fail "XMRig"
	Clean
	Config
	End_Message
	exit
}
Build_Quiet()
{
	if [[ $optionForce = "yes" ]]; then
		Build_Message "$build0"
		Overwrite_XMRig >/dev/null 2>&1
	fi
	Build_Message "$build1";Pull_XMRig >/dev/null 2>&1;Build_Fail "XMRig"
	Build_Message "$build2";Build_Folders >/dev/null 2>&1;Build_Fail "Folders"
	Build_Message "$build3";Build_Libuv >/dev/null 2>&1;Build_Fail "Libuv"
	Build_Message "$build4";Build_Hwloc >/dev/null 2>&1;Build_Fail "Hwloc"
	if [[ $optionLibre = "yes" ]]; then
		Build_Message "[5/6] Building LibreSSL";Build_LibreSSL >/dev/null 2>&1;Build_Fail "LibreSSL"
	else
		Build_Message "$build5";Build_OpenSSL >/dev/null 2>&1;Build_Fail "OpenSSL"
	fi
	Build_Message "$build6";Build_XMRig >/dev/null 2>&1;Build_Fail "XMRig"
	Clean
	Config
	End_Message
	exit
}

#
#						Package Manager Search Function
#
Search_For_PackageManager()
{
	local packageManager="$1"
	if [[ -f $packageManager ]]; then
		if [[ $packageManager = "brew" ]]; then
			$bgreen; echo -n "MacOS"
		elif [[ $packageManager = "pkg" ]]; then
			$bgreen; echo -n "FreeBSD"
		else
			$bgreen; echo -n "$distroPrettyName"
		fi
		$iwhite; echo -n " detected: using "
		$bgreen; echo "$2"
		found="yes"
		foundPackageManager="$2"
		$off
	fi
}
Which_PackageManager()
{
	Search_For_PackageManager "/usr/bin/apt" "apt" || exit
	Search_For_PackageManager "/usr/bin/pacman" "pacman" || exit
	Search_For_PackageManager "/usr/bin/dnf" "dnf" || exit
	Search_For_PackageManager "/usr/bin/pkg" "pkg" || exit
	Search_For_PackageManager "/usr/bin/brew" "brew" || exit
	Search_For_PackageManager "/usr/bin/apk" "apk" || exit
	if [[ $found != "yes" ]]; then
		$bred; echo "Package Manager not found/supported!"
		$ired; echo "Exiting..."
		exit
	fi
}

#
#						Option Functions
#
Clean()
{
	if [[ $optionClean = "yes" ]]; then
		$iwhite; echo "Cleaning up..." ;$off
		tmp="$installDirectory/tmp_autobuild"
		mkdir "$tmp"
		mv "$AutoBuild/xmrig" "$tmp"
		mv "$installDirectory/src/config.json" "$tmp"
		cd $installDirectory
		ls | grep -v "tmp_autobuild" | xargs rm -rf > /dev/null
		rm -rf .git .github .gitignore > /dev/null
		mv "$tmp/xmrig" $installDirectory
		mv "$tmp/config.json" $installDirectory
		rm -rf "$tmp" > /dev/null
	fi
}
Config()
{
	if [[ $optionClean = "yes" ]]; then
		configJson="$installDirectory/config.json"
	else
		configJson="$AutoBuild/config.json"
	fi
	if [[ $foundPackageManager = "apk" || $foundPackageManager = "brew" ]]; then
		configBasic="no"
		configAdvanced="no"
	fi
	if [[ $configBasic = "yes" || $configAdvanced = "yes" ]]; then
		$iwhite; echo "Configuring..." ;$off
		sed -i "s/donate.v2.xmrig.com:3333/$pool/g" $configJson
		sed -i "s/YOUR_WALLET_ADDRESS/$wallet/g" $configJson
		sed -i "s/\"rig-id\": null,/\"rig-id\": \"$rig\",/g" $configJson
	fi
	if [[ $configAdvanced = "yes" ]]; then
		[[ $gbPages = "yes" ]]&& sed -i "s/\"1gb-pages\": false,/\"1gb-pages\": true,/g" $configJson
		[[ $hugePages != "yes" ]]&& sed -i "s/\"huge-pages\": true,/\"huge-pages\": false,/g" $configJson
		[[ $hugePagesJit = "yes" ]]&& sed -i "s/\"huge-pages-jit\": false,/\"huge-pages-jit\": true,/g" $configJson
		[[ $keepAlive = "yes" ]]&& sed -i "s/\"keepalive\": false,/\"keepalive\": true,/g" $configJson
		[[ $tls = "yes" ]]&& sed -i "s/\"tls\": false,/\"tls\": true,/g" $configJson
	fi
}
Config_Prompt()
{
	Search_For_PackageManager >/dev/null
	Which_PackageManager >/dev/null
	if [[ $foundPackageManager = "apk" || $foundPackageManager = "brew" ]]; then
		$ired; echo "Config is only available on GNU/Linux"
	else
		[[ $interactive = "yes" ]]&& local bred="$iblue"
		if [[ $configBasic = "yes" ]]; then
			$bred; echo -n "[1/3] Pool URL+Port: " ;$bwhite;read pool
			$bred; echo -n "[2/3] Wallet: " ;$bwhite;read wallet
			$bred; echo -n "[3/3] Rig Name: " ;$bwhite;read rig
		elif [[ $configAdvanced = "yes" ]]; then
			$bred; echo -n "[1/8] Pool URL+Port: " ;$bwhite;read pool
			$bred; echo -n "[2/8] Wallet: " ;$bwhite;read wallet
			$bred; echo -n "[3/8] Rig Name: " ;$bwhite;read rig
			$bred; echo -n "[4/8] 1GB-Pages: (Y/n) " ;$bwhite;Yes(){ gbPages="yes" ;};No(){ :;};YES_no
			$bred; echo -n "[5/8] Huge-Pages: (Y/n) " ;$bwhite;Yes(){ hugePages="yes" ;};No(){ :;};YES_no
			$bred; echo -n "[6/8] Huge-Pages-JIT: (Y/n) " ;$bwhite;Yes(){ hugePagesJit="yes" ;};No(){ :;};YES_no
			$bred; echo -n "[7/8] KeepAlive: (Y/n) " ;$bwhite;Yes(){ keepAlive="yes" ;};No(){ :;};YES_no
			$bred; echo -n "[8/8] TLS: (Y/n) " ;$bwhite;Yes(){ tls="yes" ;};No(){ :;};YES_no
		fi
	fi
}

################################################          END OF HEADER CODE        ################################################
################################################        START OF QUICK BUILD        ################################################
# stupid way of skipping
if [[ $1 = "" ]]; then
	interactive="yes"
elif [[ $1 != "" ]]; then
	quickBuild="yes"
fi
if [[ $quickBuild = "yes" ]]; then

#
#						Options
#
for optionChoices in $@ ;do
	case $optionChoices in
		--stable|-S)
			optionStable="yes"
			stableColor="\033[1;32m[Stable]"
			libVersion="stable"
			;;
		--latest|-L)
			optionLatest="yes"
			latestColor="\033[1;32m[Latest]"
			libVersion="latest"
			;;
		--config|-C)
			optionConfig="yes"
			configColor="\033[1;32m[Config]"
			configAdvanced="yes"
			;;
		--path=*)
			optionPath="yes"
			pathColor="\033[1;32m[Path]"
			pathLong="yes"
			;;
		-P=*)
			optionPath="yes"
			pathColor="\033[1;32m[Path]"
			pathShort="yes"
			;;
		--dev|-D)
			optionDev="yes"
			devColor="\033[1;32m[Dev]"
			;;
		--clean|-c)
			optionClean="yes"
			cleanColor="\033[1;32m[Clean]"
			;;
		--libre|-l)
			optionLibre="yes"
			libreColor="\033[1;32m[Libre]"
			;;
		--deps|-d)
			optionDeps="yes"
			depsColor="\033[1;32m[Dependencies]"
			;;
		--quiet|-q)
			optionQuiet="yes"
			quietColor="\033[1;32m[Quiet]"
			;;
		--force|-f)
			optionForce="yes"
			forceColor="\033[1;32m[Force]"
			;;
		--help|-h)
			optionHelp="yes"
			;;
		*)
			$ired; echo "XMRig-Auto-Build: invalid options!"
			$off; echo "for help: ./XMRig-Auto-Build --help"
			exit
	esac
done

# help option
if [[ $optionHelp = "yes" ]]; then
	Print_Help
	exit
fi

# library error
if [[ $optionStable != "yes" && $optionLatest != "yes" ]]; then
	$ired; echo "XMRig-Auto-Build: pick a library version!"
	exit
fi

# multiple library error
if [[ $optionStable = "yes" && $optionLatest = "yes" ]]; then
    $ired; echo "XMRig-Auto-Build: pick only 1 library version!"
	exit
fi

# really really really stupid way to filter input for path
if [[ $optionPath = "yes" ]]; then
	for i in $@ ;do
		if [[ $pathLong = "yes" ]]; then
			inputPath="$(echo $i | grep -- --path= | sed 's/--path=//g')"
			if [[ $inputPath = *"/"* ]]; then
				break
			fi
		elif [[ $pathShort = "yes" ]]; then
			inputPath="$(echo $i | grep -- -P= | sed 's/-P=//g')"
			if [[ $inputPath = *"/"* ]]; then
				break
			fi
		fi
	done
	installDirectory="$inputPath/xmrig"
	AutoBuild="$installDirectory/AutoBuild"
	deps="$AutoBuild/deps"
	libBuild="$AutoBuild/libBuild"
	if [[ ! -d $inputPath ]]; then
		$ired; echo "XMRig-Auto-Build: install path does not exist!"
		exit
	fi
fi
colorAll_1="$stableColor $latestColor $configColor $pathColor $devColor"
colorAll_2="$cleanColor $depsColor $quietColor $libreColor $forceColor"

#
#						Quick Build Function
#
Quick_Build_Prompt()
{
	$bred; echo "                 XMRig-Auto-Build                  "
	$bred; echo "###################################################"
	$bred; echo "                      Options:"
	$off; echo -e "     $colorAll_1"
	$off; echo -e "  $colorAll_2"
	echo
	$bred; echo -n "Install path: "
	$bwhite; echo "$installDirectory"
	[[ $optionConfig = "yes" ]]&& Config_Prompt
	echo
	$bred; echo "                    Start? (Y/n)"
	$bred; echo "###################################################"
	echo -n "                          "
}

#
#						Quick Build
#
Quick_Build_Prompt
Yes()
{
	# /xmrig/ check
	if [[ $optionForce != "yes" ]]; then
		if [[ -d "$installDirectory" ]]; then
			$ired; echo -n "Folder: "
			$bwhite; echo -n "$installDirectory"
			$ired; echo " already exists!"
			$ired; echo "Exiting..."
			exit
		fi
	fi
	# build dependencies
	if [[ $optionDeps = "yes" ]]; then
		Search_For_PackageManager
		Which_PackageManager
		Build_Dependencies
	fi
	# actual build
	if [[ $optionQuiet = "yes" ]]; then
		Build_Quiet
	else
		Build_All
	fi
}
No(){ $ired; echo "Exiting..." ;exit;}
YES_no

# stupid way of skipping
fi

################################################                END OF QUICK BUILD        ################################################
################################################        START OF INTERACTIVE BUILD        ################################################
#
#						Initial Prompt
#
$bgreen; echo "########################"
$bgreen; echo "#   XMRig-Auto-Build   #"
$bgreen; echo "########################"
$bblue; echo -n "Install into "
$bwhite; echo -n "${installDirectory}? "
$bgreen; echo -n "(Y/n) " ;$off
Yes(){ $iwhite; echo "Starting..." ;}
No(){ $ired; echo "Exiting..." ;exit; }
YES_no

#
#						Check If /xmrig/ Already Exists
#
if [[ -d "$installDirectory" ]]; then
	$ired; echo -n "Folder: "
	$bwhite; echo -n "$installDirectory"
	$ired; echo " already exists!"
	$ired; echo -n "Continue anyway? (y/N) "
	Yes()
	{
		$iwhite; echo "Continuing..."
		optionForce="yes"
	}
	No(){ $ired; echo "Exiting..." ;exit;}
	yes_NO
fi

#
#						Installing Dependencies
#
$bblue; echo -n "Install build dependencies? "
$bgreen; echo -n "(Y/n) " ;$off
Yes()
{
	Search_For_PackageManager
	Which_PackageManager
	Build_Dependencies
}
No(){ $iwhite; echo "Skipping build dependencies..." ;}
YES_no

#
#						Pick Library Version
#
Lib_Yesno()
{
	$bblue; echo -n "Use [$libVersion]? "
	$bgreen; echo -n "(Y/n) " ;$off
	read yn
	if [[ $yn = "" || $yn = "y" || $yn = "Y" ||$yn = "yes" ||$yn = "Yes" ]]; then
		libFinalChoice="yes"
	fi
}
while true; do
	$bblue; echo -n "Which library versions to build? "
	$bgreen; echo -n "[ Stable / latest ] " ;$off
	read answer
		case $answer in
		Stable|stable|"")
			libVersion="stable"
			Lib_Yesno
			[[ $libFinalChoice = "yes" ]]&&break
			;;
		Latest|latest)
			libVersion="latest"
			Lib_Yesno
			[[ $libFinalChoice = "yes" ]]&&break
			;;
		*)
			$ired; echo "Error, please type valid version"
			;;
	esac
done
$iwhite; echo "[$libVersion] selected..."

#
#						Pick XMRig Version
#
XMRig_Yesno()
{
	$bblue; echo -n "Use [$xmrigVersion]? "
	$bgreen; echo -n "(Y/n) " ;$off
	read yn
	if [[ $yn = "" || $yn = "y" || $yn = "Y" ||$yn = "yes" ||$yn = "Yes" ]]; then
		xmrigFinalChoice="yes"
	fi
}
while true; do
	$bblue; echo -n "Which XMRig version to build? "
	$bgreen; echo -n "[ Stable / dev ] " ;$off
	read answer
		case $answer in
		Stable|stable|"")
			xmrigVersion="stable"
			XMRig_Yesno
			[[ $xmrigFinalChoice = "yes" ]]&&break
			;;
		Dev|dev)
			xmrigVersion="dev"
			optionDev="yes"
			XMRig_Yesno
			[[ $xmrigFinalChoice = "yes" ]]&&break
			;;
		*)
			$ired; echo "Error, please type valid version"
			;;
	esac
done
$iwhite; echo "[$xmrigVersion] selected..."

#
#						Configure config.json
#
while true; do
	$bblue; echo -n "Configure config.json: "
	$bgreen; echo -n "[ Basic / advanced / skip ] " ;$off
		read answer
		case $answer in
		basic|Basic|"")
			configBasic="yes"
			break
			;;
		advanced|Advanced)
			configAdvanced="yes"
			break
			;;
		skip|Skip)
			$iwhite; echo "Skipping config..."
			break
			;;
		*)
			$ired; echo "Error, please type valid answer"
	esac
done
if [[ $configBasic = "yes" ]]; then
	$bgreen; echo "[Basic]:"
elif [[ $configAdvanced = "yes" ]]; then
	$bgreen; echo "[Advanced]:"
fi
Config_Prompt

#
#						Cleanup Prompt
#
$bblue; echo -n "Delete source code after build? "
$bgreen; echo -n "(Y/n) " ;$off
Yes()
{
	$iwhite; echo "Will delete source code after build..."
	optionClean="yes" ;}
No(){ $iwhite; echo "Skipping cleanup..." ;}
YES_no

#
#						Build
#
$bred; echo "#####################################"
$bred; echo "#   Start XMRig-Auto-Build? (Y/n)   #"
$bred; echo "#####################################"
$off
Yes(){ $iwhite; echo "Starting..." ;$off; }
No(){ $ired; echo "Exiting..." ;$off;exit; }
echo -n "                  "
YES_no
Build_All

################################################        END OF INTERACTIVE BUILD        ################################################
